In [36]:
# Reverse the Words in a String
# Input:s = "Python is awesome"
# Output:"awesome is Python"

str1 = "Python is awesome"
print("Reversed string - "," ".join(str1.split()[::-1]))
print("Reversed each word in string - ",str1[::-1])
print("Revresed string without [::-1] - ","".join([str1[len(str1) - i] for i in range(1, len(str1)+1)]))

Reversed string -  awesome is Python
Reversed each word in string -  emosewa si nohtyP
Revresed string without [::-1] -  emosewa si nohtyP

In [9]:
# Find the First Non-Repeating Character
# Input: "aabbccdeff"
# Output: "d"

str1 = "aabbccdeff"
count = {}

for i in str1:
    if i not in count:
        count[i] = 1
    else:
        count[i] = count[i] + 1

print("First Non-Repeating Character - ",[key for key in count.keys() if int(count[key]) == 1 ][0])

First Non-Repeating Character -  d

In [19]:
# Convert list into dataframe
employees = [
    {"Name": "John", "Age": 25, "Salary": 50000},
    {"Name": "Alice", "Age": 30, "Salary": 65000},
    {"Name": "Bob", "Age": 28, "Salary": 55000}
]

import pandas as pd 

df = pd.DataFrame(employees)
print(df)

# convert mult list in df 

names = ["John", "Alice", "Bob"]
ages = [25, 30, 28]

df1 = pd.DataFrame()
df1["Names"] = names
df1["ages"] = ages
df1

#Add a new column Bonus which is 10% of Salary.
df["Nonus"] = [df["Salary"][i]*10/100 for i in range(len(df["Salary"]))]
df

    Name  Age  Salary
0   John   25   50000
1  Alice   30   65000
2    Bob   28   55000

    Name  Age  Salary   Nonus
0   John   25   50000  5000.0
1  Alice   30   65000  6500.0
2    Bob   28   55000  5500.0

In [21]:
# Convert a DataFrame Back into a List
Age = list(df['Age'])
print(Age)

# A list of dictionaries.
dict1 = {"Name":list(df['Name']), "Age":list(df['Age'])}
dict1

[25, 30, 28]

{'Name': ['John', 'Alice', 'Bob'], 'Age': [25, 30, 28]}

In [33]:
# Convert to dict
emp_no = [1, 2, 3]
emp_name = ["Shreyas", "Saurabh", "Rohit"]

result_dic = {emp_no[i]:emp_name[i] for i in range(len(emp_name))}
result_dic

# OR 
result_dic2 = dict(zip(emp_no,emp_name))
print(result_dic2)

l2 = emp_no
print("L2 copy %s",l2)
l2.append(100)
print("emp_no after append %s",emp_no)

{1: 'Shreyas', 2: 'Saurabh', 3: 'Rohit'}
L2 copy %s [1, 2, 3]
emp_no after append %s [1, 2, 3, 100]

In [35]:
# Remove duplicate elements while preserving order

nums = [1, 2, 3, 2, 4, 5, 1, 6]
dup_om = []
for i in nums:
    if i not in dup_om:
        dup_om.append(i)
dup_om

[1, 2, 3, 4, 5, 6]

In [40]:
# Count the frequency of each word in a sentence

sentence = "python is easy and python is powerful"

count = {}
for i in sentence.split():
    if i in count:
        count[i] = count[i] + 1
    else:
        count[i] = 1

count

{'python': 2, 'is': 2, 'easy': 1, 'and': 1, 'powerful': 1}

In [67]:
#  Merge two dictionaries (sum values of common keys)

dict1 = {'a': 10, 'b': 20, 'c': 30}
dict2 = {'b': 15, 'c': 5, 'd': 40}

result_dict = dict1.copy()

for i, v in dict2.items():
    result_dict[i] = result_dict.get(i,0) + v

result_dict

{'a': 10, 'b': 35, 'c': 35, 'd': 40}

In [75]:
# Find the second largest number without using sort()

numbers = [12, 45, 7, 89, 23, 89]

temp = []
for i in numbers:
    if i != max(numbers):
        temp.append(i)

max(temp)

45

In [84]:
# Split a list into batches of size N

numbers = [1,2,3,4,5,6,7,8,9,10]
batch_size = 2

batch = []
for i in range(0, len(numbers), batch_size):
    batch.append(numbers[i:i+batch_size])

batch

[[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]

In [85]:
# Find the common elements between two lists

list1 = [1,2,3,4,5]
list2 = [4,5,6,7]

common_elements = [i for i in list1 if i in list2]
common_elements

[4, 5]

In [94]:
# Rotate a list to the right by K positions

numbers = [1,2,3,4,5]
k = 3

numbers[-k:]+numbers[:-k]

[3, 4, 5, 1, 2]

In [ ]:
# table of 7 until 1000 number 
m = 7 

re = []
for i in range(1000):
    if re == []:
        re.append(7)
    else:
        sum = re[-1]+m
        if sum > 1000:
            break
        re.append(sum)
    

re

[4, 5]

In [ ]:
# use the taple to do the same as above

In [1]:
# input = "AaBb!abaCdc"
 
# Rules:
 
# Ignore special characters, digits, and spaces.
# Treat uppercase and lowercase letters as the same.
# Count the frequency of each alphabet.
# Sort by frequency (descending), then alphabetically.
# Append the total number of valid alphabets at the end as total<count>.
 
# Processing:
# a -> 4
# b -> 3
# c -> 2
# d -> 1
 
# Total alphabets = 10
 
# Expected output:
# a4b3c2d1total10

In [2]:
input = "AaBb!abaCdc"

result = {}
for i in input.lower():
    if i.isalpha():
        # print(i)
        if i not in result:
            result[i] = 1
        else:
            result[i] = result[i] + 1

total = sum(list(result.values()))
re_temp = []
for i, v in result.items():
    re_temp.append(i)
    re_temp.append(str(v))
final_result = "".join(re_temp) + f"total{total}"
final_result

'a4b3c2d1total10'

In [ ]:
# Check if two strings are anagrams
str1 = "listen"
str2 = "silent"

def ang(str1,str2):
    if "".join(sorted(str1)) == "".join(sorted(str2)):
        return True
    return False

ang(str1,str2)

True

In [11]:
# Find missing number 
numbers = [1,2,3,5,6,7]

max(numbers)
missing = [i for i in range(1, max(numbers)) if i not in numbers]
missing

[4]

In [12]:
# Move all 0 to the end 
numbers = [1,0,5,0,2,3]

temp = []
new_no = []

for i in numbers:
    if i == 0:
        temp.append(i)
    else:
        new_no.append(i)

new_no+temp

[1, 5, 2, 3, 0, 0]

In [17]:
#check for palamdorm

text = "madam"

if text == text[::-1]:
    print(True)
else:
    print(False)

True

In [3]:
# Find the intersection of three lists
list1 = [1,2,3,4]
list2 = [2,3,5]
list3 = [3,2,6]

for i in list1:
    if i in list2 and list3:
        print(i)

2
3

In [24]:
# Find maximum occurring character
text = [1,2,2,3,4,4,5]#"programmingg"

word_count = {}

for i in text:
    if i not in word_count:
        word_count[i] = 1
    else:
        word_count[i] = word_count[i] + 1

for i,v in word_count.items():
    if v == min(word_count.values()):
        print(f"max character- {i} count- {v}")

max character- 1 count- 1
max character- 3 count- 1
max character- 5 count- 1

In [22]:
numbers = [1,2,2,3,4,4,5]

re = []
for i in numbers:
    print(i)
    if i not in re:
        re.append(i)

1
2
2
3
4
4
5

In [23]:
re

[1, 2, 3, 4, 5]

In [4]:
#Given a list of intervals, merge all overlapping intervals

intervals = [
    [1,3],
    [2,6],
    [8,10],
    [15,18]
]

re = []
for i in range(len(intervals)):
    if len(intervals) - 1 == i:
         break
    # print(intervals[i])
    if intervals[i][1:] > intervals[i+1][:1]:
        re.append([intervals[i][:1][0],intervals[i+1][1:][0]])
    else:
        re.append(intervals[i])
    # break

re

[[1, 6], [2, 6], [8, 10]]

In [2]:
# Group Employees by Department

# Given a list of employee records, group employees by department and calculate:
# Total employees
# Average salary

employees = [
    {"name":"John","dept":"IT","salary":50000},
    {"name":"Alice","dept":"HR","salary":40000},
    {"name":"Bob","dept":"IT","salary":70000},
    {"name":"Mike","dept":"HR","salary":60000},
    {"name":"David","dept":"IT","salary":90000}
]

import pandas as pd 
df = pd.DataFrame(employees)
df

    name dept  salary
0   John   IT   50000
1  Alice   HR   40000
2    Bob   IT   70000
3   Mike   HR   60000
4  David   IT   90000

In [8]:
result = df.groupby("dept")["salary"].agg(
    count="count",
    average_salary="mean"
)

print(result)

      count  average_salary
dept
HR        2         50000.0
IT        3         70000.0

In [58]:
result = {}

for i in employees:
    dept = i["dept"]
    if result :
        if "IT" in result and "HR" in result:
            count = result[dept].get("count") + 1
            total_salary = result[dept].get("total_salary") + i['salary']
    else:
        count = 1
        total_salary = i['salary']
    result[dept] = {"count":count, "total_salary": total_salary}

result

{'IT': {'count': 3, 'total_salary': 210000},
 'HR': {'count': 2, 'total_salary': 110000}}

In [59]:
for i in result.keys():
    print(result[i]["total_salary"])
    result[i]["total_salary"] = result[i]["total_salary"]/ result[i]["count"]

210000
110000

In [60]:
result

{'IT': {'count': 3, 'total_salary': 70000.0},
 'HR': {'count': 2, 'total_salary': 55000.0}}

In [10]:
#Find the Top K Frequent Words

text = """
python is easy
python is powerful
python is popular
data science uses python
"""

k = 2

In [ ]:
freq_words = {}
for i in text.split():
    if i not in freq_words:
        freq_words[i] = 1
    else:
        freq_words[i] = freq_words[i] + 1
    # print(i)
list(freq_words.items())[:k]

[('python', 4), ('is', 3)]